### PR TITLE
fix: update the size of the sample text that determines axis padding

### LINKED ISSUE #363: Axis padding should account for a thorough set of skinny characters
Axis padding to the left of the y-axis is too small when the sample tick contains a number '1' in the text. This makes the sample tick skinnier than other ticks that have large characters, causing them to become partially hidden.

The sample tick should check against a bigger set of skinny characters to ensure that its width is wide enough to ensure that all ticks' labels will not be hidden.

Here is an example of the problem. Notice the highest tick on the y-axis has a partially hidden label making the '2' difficult to read:
Screen Shot 2020-11-04 at 6 10 55 PM

### PR DESCRIPTION
**Pull request by TCL735**
Closes #363 

Look for more skinny characters when updating the the sample text that determines axis padding. This will improve readability and prevent axis tick labels from being cut off on the y-axis.

### CODE REVIEW

**Comment by TCL735** [comment]
@hoorayimhelping i think you had mentioned some comments on this previously. adding you to this review to get your take on it.

File: giraffe/src/utils/getTextMetrics.ts [hunk 1]
```diff
@@ -3,6 +3,40 @@ export interface TextMetrics {
...
+    const char = text.charAt(index)
+    if (
+      char === '-' ||
+      char === '1' ||
+      char === '|' ||
+      char === 'i' ||
+      char === 'l' ||
+      char === 'I' ||
+      char === '!'
+    ) {
```
Comment (hoorayimhelping) [inline giraffe/src/utils/getTextMetrics.ts:33]: alternative es6 foxy form:
```ts
const SLENDER_BOIS = ['-', '1', '|', 'i', 'l', 'I', '!']

if (SLENDER_BOIS.includes(char)) {
  sample += char
}
```

**Review by hoorayimhelping — APPROVED** [review]
gotta be honest: it's fairly janky, but let's see how it goes

**Review by Palakp41 — APPROVED** [review]

File: giraffe/src/utils/getTextMetrics.ts (hunk 1 above)
Comment (TCL735) [reply giraffe/src/utils/getTextMetrics.ts:33]: i like this, will use it.

Comment (subirjolly) [reply giraffe/src/utils/getTextMetrics.ts]: Quick quesiton. How long is this "text" usually?

Comment (TCL735) [reply giraffe/src/utils/getTextMetrics.ts]: 10 million characters. No, just kidding. A typical tick label on an axis. For example, "1.00", "1.10". Or even time, "2020-11-09 1:09:33 PM PST". Generally, not very long because it is visual information.

Comment (subirjolly) [reply giraffe/src/utils/getTextMetrics.ts]: haha. ah i see. thank you!
