### PR TITLE
fix: use separator for large numbers

### LINKED ISSUE #295: Bug: Gauge value sometimes does not have numeric separators for large numbers
Gauge values follow the localeString format by putting in the appropriate numeric separators for large numbers. For the U.S., the separator is a comma.

Most of the time, the commas are present in large numbers. But sometimes, the comma is missing. This happens when the number includes a decimal portion and the decimal portion ends in zero. Previously, a tangentially related issue - https://github.com/influxdata/giraffe/issues/284 - addressed the position of the needle.

Unresolved is the actual number rendered in the Gauge. It still does not correctly display numbers with decimals that end with 0. It is missing the comma separator.

Here is an example. The rendered number should be **8,264.9530** - with the comma separator
Screen Shot 2020-09-25 at 4 12 15 PM

### PR DESCRIPTION
**Pull request by TCL735**
Closes #295 

Allows large numbers that end with decimal 0 to have numeric separators.
Screen Shot 2020-09-25 at 6 55 58 PM

### CODE REVIEW

File: giraffe/src/utils/formatStatValue.ts [hunk 1]
```diff
@@ -35,14 +35,20 @@ export const formatStatValue = (
...
   if (isNumber(value)) {
-    const roundedValue = Number(value).toFixed(digits)
-    const endsWithZero = /\.[1-9]{0,}0{1,}$/
-
-    localeFormattedValue = endsWithZero.test(roundedValue)
-      ? roundedValue
-      : Number(roundedValue).toLocaleString(undefined, {
-          maximumFractionDigits: MAX_DECIMAL_PLACES,
-        })
+    const roundedValueAndDecimal = Number(value)
```
Comment (hoorayimhelping) [inline giraffe/src/utils/formatStatValue.ts:38]: minor suggestion: use [array destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Examples) to make more self documenting code:
```ts
    const [wholeNumber, fractionalNumber] = Number(value).toFixed(digits).split('.')
```

then you can do something like

```ts
if (fractionalNumber) {
  ...
}
```

**Review by hoorayimhelping — APPROVED** [review]

File: giraffe/src/utils/formatStatValue.ts (hunk 1 above)
Comment (TCL735) [reply giraffe/src/utils/formatStatValue.ts:38]: Excellent suggestion. Done.
